from setuptools import find_packages, setup

setup(
    name="insurance_retention_predictor",
    version="0.1.0",
    description="预测保险客户续保行为的机器学习系统",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(),
    python_requires=">=3.8",
    install_requires=[
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "scikit-learn>=1.3.0",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "plotly>=5.14.0",
        "xgboost>=1.7.0",
        "lightgbm>=4.0.0",
        "catboost>=1.2",
        "tensorflow>=2.12.0",
        "keras>=2.12.0",
        "shap>=0.41.0",
        "lime>=0.2.0",
        "mlflow>=2.3.0",
        "optuna>=3.1.0",
        "fastapi>=0.95.0",
        "uvicorn>=0.22.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.3.0",
            "black>=23.3.0",
            "flake8>=6.0.0",
            "isort>=5.12.0",
            "pre-commit>=3.3.0",
            "jupyter>=1.0.0",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Financial and Insurance Industry",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
) 